### PR TITLE
Create documentation with write-the

### PR DESCRIPTION
**Pull request by Wytamma**
Hi @eimenhmdt,

Awesome project! I've also been working on a GPT-CLI `write-the` (https://github.com/wytamma/write-the). I used the commands `write-the docs` and `write-the mkdocs` to create documentation for autoresearcher. 

You can see a demo version of the site here -> https://blog.wytamma.com/autoresearcher/

Screen Shot 2023-04-17 at 10 22 00 am

Screen Shot 2023-04-17 at 10 23 09 am

### CODE REVIEW

**Comment by eimenhmdt** [comment]
Hey @Wytamma! Wow, that's awesome. Love it. And it updates the documentation automatically, right?

**Comment by Wytamma** [comment]
@eimenhmdt yep it pulls the API reference from the docstrings (e.g. https://github.com/eimenhmdt/autoresearcher/pull/17/files#diff-42c29c39426f197ccabc16a23fec3165c29926d31599caac364d28c02cd1dc82R1) so if you update the docstrings it'll recreate the docs. If the code structure changes or you add new functions etc you can regenerate the docs with `write-the mkdocs autoresearcher` and that'll pull any functions with docstrings into the reference. 

To get the site to go live you'll just have change your pages settings i.e. 
image

**Comment by eimenhmdt** [comment]
That sounds excellent. Thanks for this amazing contribution!!

**Comment by eimenhmdt** [comment]
Sorry, maybe a stupid question haha, but how do I get the page to look like the demo page you sent me?  :D

https://eimenhmdt.github.io/autoresearcher/

**Comment by Wytamma** [comment]
Ah you need to setup GitHub-Pages to deploy from the `gh-pages` branch should be here -> https://github.com/eimenhmdt/autoresearcher/settings/pages 
image

**Comment by eimenhmdt** [comment]
It worked! Thank you so much!!

**Pull request merged**
